dist: bionic
addons:
  apt:
    update: true
    packages:
      - libboost-test-dev
language: cpp
script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake ../build .
  - cmake ../build . --target package