dist: bionic
addons:
  apt:
    update: true
    packages:
      - libgtest-dev
      - build-essential
      - cmake
language: cpp
before_script:
  - cd /usr/src/gtest
  - sudo -E cmake .
  - sudo -E cmake --build . --target install
  - cd $TRAVIS_BUILD_DIR
script:
  - mkdir build
  - cd build
  - cmake ../source
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukerkerker:$BINTRAY_API_KEY "https://api.bintray.com/content/kerkerker/otus-cpp-course/bulk/0.0.$TRAVIS_BUILD_NUMBER/bulk-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    branch: 07.homework