dist: bionic
addons:
  apt:
    update: true
    packages:
      - libboost-test-dev
language: cpp
script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
  - cmake --build . --target package
env:
  - PACKAGE_VERSION=0.0.$TRAVIS_BUILD_NUMBER
  - PROJECT_NAME=hello_world
  - PACKAGE_NAME=$PROJECT_NAME-$PACKAGE_VERSION-Linux.deb
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T $PACKAGE_NAME -ukerkerker:$BINTRAY_API_KEY "https://api.brkerker/otus-cpp-course/$PROJECT_NAME/$PACKAGE_VERSION/$PACKAGE_NAME;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    branch: 01.homework